version: 2




models:
  - name: stg_gcp_billing_companies
    columns:
      - name: company_id
        tests:
          - unique
          - not_null
      - name: company_name
        tests:
          - unique
          - not_null
  - name: stg_gcp_billing_product_usage
    columns:
      - name: company_id
        tests:
          - not_null:
              severity: warn
          - relationships:
              to: ref('stg_gcp_billing_companies')
              field: company_id
      - name: product_account_id
        tests:
          - not_null:
              severity: warn
      - name: product_usage_billing_ts
        tests:
          - not_null:
              severity: warn
      - name: product_id
        tests:
          - not_null:
              severity: warn
