version: 2

sources:
  - name: custom_source_1
    database: ra-development
    schema: custom_schema_1
    tables:
      - name: s_customers
        identifier: customers
        loaded_at_field: _loaded_at
      - name: s_contacts
        identifier: contacts
        loaded_at_field: _loaded_at
      - name: s_accounts
        identifier: accounts
        loaded_at_field: _loaded_at
      - name: s_transactions
        identifier: transactions
        loaded_at_field: _loaded_at
      - name: s_products
        identifier: products
        loaded_at_field: _loaded_at
      - name: s_users
        identifier: users
        loaded_at_field: _loaded_at
      - name: s_events
        identifier: events
        loaded_at_field: _loaded_at
      - name: s_projects
        identifier: projects
        loaded_at_field: _loaded_at
      - name: s_usage
        identifier: usage
        loaded_at_field: _loaded_at
