version: 2

sources:
  - name: stitch_asana_projects
    database: "{{ var('stg_asana_projects_stitch_database') }}"
    schema: "{{ var('stg_asana_projects_stitch_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _sdc_batched_at

    tables:
      - name: workspaces
      - name: projects
      - name: tasks
      - name: users
