version:  2

models:
  - name: stg_github_starrers_contacts
    description: "Github Repo Starrer Contacts"
    columns:
      - name: contact_id
        tests:
          - unique
          - not_null
      - name: contact_name
        tests:
          - not_null:
              severity: warn
