version: 2

sources:
  - name: fivetran_mixpanel_events
    database: "{{ var('stg_mixpanel_events_fivetran_database') }}"
    schema: "{{ var('stg_mixpanel_events_fivetran_schema') }}"



    tables:
      - name: event

  - name: stitch_mixpanel_events
    database: "{{ var('stg_mixpanel_events_stitch_database') }}"
    schema: "{{ var('stg_mixpanel_events_stitch_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _sdc_batched_at

    tables:
      - name: event
        identifier: mixpanel_export
