version: 2

sources:
  - name: fivetran_docusign
    database: "{{ var('stg_docusign_contracts_fivetran_database') }}"
    schema: "{{ var('stg_docusign_contracts_fivetran_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _fivetran_synced

    tables:
      - name: docusign_envelopes
