version: 2

sources:
  - name: stitch_hubspot_crm
    database: "{{ var('stg_hubspot_crm_stitch_database') }}"
    schema: "{{ var('stg_hubspot_crm_stitch_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _sdc_batched_at

    tables:
      - name: companies
      - name: contacts
      - name: deals
      - name: owners
      - name: deal_pipelines
      - name: pipeline_stages
      - name: engagements

  - name: fivetran_hubspot_crm
    database: "{{ var('stg_hubspot_crm_fivetran_database') }}"
    schema: "{{ var('stg_hubspot_crm_fivetran_schema') }}"



    tables:
      - name: companies
        identifier: company
      - name: contacts
        identifier: contact
      - name: deals
        identifier: deal
      - name: owners
        identifier: owner
      - name: deal_pipelines
        identifier: pipeline
      - name: pipeline_stages
        identifier: pipeline_stage
      - name: deal_companies
        identifier: deal_company
      - name: engagements
        identifier: engagements
      - name: property_history
