version: 2

sources:
  - name: segment
    database: "{{ var('stg_segment_events_segment_database') }}"
    schema: "{{ var('stg_segment_events_segment_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: uuid_ts

    tables:
      - name: pages
      - name: tracks
      - name: users
