version: 2

sources:
  - name: stitch_hubspot_email
    database: "{{ var('stg_hubspot_email_stitch_database') }}"
    schema: "{{ var('stg_hubspot_email_stitch_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _sdc_batched_at

    tables:
      - name: email_events
      - name: campaigns
