version: 2

sources:
  - name: calendly_meetings
    database: "{{ var('stg_calendly_meetings_database') }}"
    schema: "{{ var('stg_calendly_meetings_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: timestamp

    tables:
      - name: discovery
        identifier: meetings_booked
