version: 2

sources:
  - name: humaans_hr
    database: "{{ var('stg_humaans_hr_database') }}"
    schema: "{{ var('stg_humaans_hr_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _sdc_batched_at

    tables:
      - name: contacts
        identifier: humaans_people
      - name: roles
        identifier: humaans_job_roles
      - name: time_off
        identifier: humaans_time_off
